---

- hosts: localhost
  tasks:
    - name: lookup SSH private key
      debug: msg="{{ lookup('amazon.aws.aws_ssm', '/test/hybrid/ssh_private', region='us-west-2' ) }}"
      register: sysops_private_key
    - name: lookup SSH public key
      debug: msg="{{ lookup('amazon.aws.aws_ssm', '/test/hybrid/ssh_public', region='us-west-2' ) }}"
      register: sysops_public_key
    - name: Add sysops user
      user:
        name: sysops
        shell: /bin/bash
        password: '!'
    - name: Add sysops user to the sudoers
      copy:
        dest: "/etc/sudoers.d/sysops"
        content: "sysops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Create .ssh directory
      copy:
        dest: "/home/sysops/.ssh/"
        state: directory
        group: sysops
        owner: sysops
        directory_mode: 0700
    - name: Add private SSH key
      copy:
        dest: "/home/sysops/.ssh/id_ed25519"
        content: sysops_private_key.stdout
        group: sysops
        owner: sysops
        mode: 0600
    - name: Deploy Authorized SSH Key
      authorized_key: 
        user: sysops
        key: "{{ sysops_public_key.stdout }}"
        state: present
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
    - name: Disable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - restart ssh
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted