---

- hosts: localhost
  tasks:
    - name: Add sysops user
      user:
        name: sysops
        shell: /bin/bash
        password: '!'
    - name: Add sysops user to the sudoers
      copy:
        dest: "/etc/sudoers.d/sysops"
        content: "sysops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Add private SSH key
      copy:
        dest: "/home/sysops/.ssh/id_ed25519"
        content: "{{ ssm_sysops_private_key }}"
        group: sysops
        owner: sysops
        mode: 0600
        directory_mode: 0700
    - name: Deploy Authorized SSH Key
      authorized_key: 
        user: sysops
        key: "{{ ssm_sysops_public_key }}"
        state: present
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
    - name: Disable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - restart ssh
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted