---

- hosts: localhost
  tasks:
    - name: lookup SSH private key
      debug: msg="{{ lookup('amazon.aws.aws_ssm', '/test/hybrid/ssh_private', region='us-west-2' ) }}"
      register: sysops_private_key
    - name: lookup SSH public key
      debug: msg="{{ lookup('amazon.aws.aws_ssm', '/test/hybrid/ssh_public', region='us-west-2' ) }}"
      register: sysops_public_key
    - name: lookup CA certificate
      debug: msg="{{ lookup('amazon.aws.aws_ssm', '/test/hybrid/ca.crt', region='us-west-2' ) }}"
      register: ca_crt
    - name: Create ssl directory
      file:
        path: "/etc/kubernetes/ssl/"
        state: directory
        group: root
        owner: root
        mode: 0755
    - name: Add ca.crt file
      copy:
        dest: "/etc/kubernetes/ssl/ca.crt"
        content: "{{ ca_crt.msg }}"
        group: root
        owner: root
        mode: 0644
    - name: Add sysops user
      user:
        name: sysops
        shell: /bin/bash
        password: '!'
    - name: Add sysops user to the sudoers
      copy:
        dest: "/etc/sudoers.d/sysops"
        content: "sysops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Create .ssh directory
      file:
        path: "/home/sysops/.ssh/"
        state: directory
        group: sysops
        owner: sysops
        mode: 0700
    - name: Add private sysops SSH key to sysops user
      copy:
        dest: "/home/sysops/.ssh/id_ed25519"
        content: "{{ sysops_private_key.msg }}"
        group: sysops
        owner: sysops
        mode: 0600
    - name: Add private sysops SSH key to root user
      copy:
        dest: "/root/.ssh/id_ed25519"
        content: "{{ sysops_private_key.msg }}"
        group: root
        owner: root
        mode: 0600
    - name: Deploy Authorized SSH Key
      authorized_key: 
        user: sysops
        key: "{{ sysops_public_key.msg }}"
        state: present
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
    - name: Disable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - restart ssh
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted