---

- hosts: localhost
  tasks: 
    - name: Clone Kubespray
      git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: /ssm/external/kubespray
        single_branch: yes
        version: v2.23.0
    - name: Install dependencies
      command:
        chdir: /ssm/external/kubespray/
        cmd: pip install -r requirements.txt