---

- hosts: localhost
  tasks: 
    - name: Clone Kubespray
      git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: /ssm/external/kubespray
        single_branch: yes
        version: v2.23.0
    - name: Install dependencies
      command:
        chdir: /ssm/external/kubespray/
        cmd: pip install -r requirements.txt
    - name: Copy inventory folder
      copy:
        src: /ssm/external/kubespray/inventory/sample
        remote_src: true
        dest: /ssm/external/kubespray/inventory/mycluster
        force: false
#    - name: Specify node IPs
#      shell: /bin/bash declare -a IPS=(10.66.1.164 10.66.1.152 10.66.1.25)
#      args:
#        chdir: /ssm/external/kubespray/
    - name: Build inventory
      command:
        chdir: /ssm/external/kubespray/
        cmd: CONFIG_FILE=inventory/mycluster/hosts.yaml python3 contrib/inventory_builder/inventory.py 10.66.1.164 10.66.1.152 10.66.1.25