- hosts: {{ node_to_label }}
  tasks:
    - name: Label node
      shell: "kubectl --kubeconfig /ssm/kubeconfig label node {{ inventory_hostname }} {{ item.key }}={{ item.value }}"
      loop: "{{ labels | dict2items }}"
      delegate_to: 127.0.0.1