---

- hosts: localhost
  tasks:
    - name: create partition for local cache
      parted:
        device: /dev/nvme1n1
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 150GiB
    - name: create partition for distributed cache
      parted:
        device: /dev/nvme1n1
        number: 2
        flags: [ lvm ]
        state: present
        part_start: 150GiB
        part_end: 100%
    - name: create volume group for local cache
      lvg:
        vg: csi-lvm-local-cache
        pvs: /dev/nvme1n1p1
    - name: create volume group for distributed cache
      lvg:
        vg: csi-lvm-distributed-cache
        pvs: /dev/nvme1n1p2
    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present