#local_cache_disk:
#  name: /dev/nvme1n1p1
#  partition: 1
#  size: 150GiB
#distributed_cache_disks:
#  - name: /dev/nvme1n1p1
#    partition: 2
#    size: 100%
---

- hosts: localhost
  tasks:
    - name: create partition for local cache
      parted:
        device: "{{ local_cache_disk.name }}"
        number: "{{ local_cache_disk.partition | default(1) }}"
        flags: [ lvm ]
        state: present
        part_end: "{{ local_cache_disk.size | default('150GiB')}}"
      register: local_cache_partition
    - name: create partitions for distributed cache
      parted:
        device: "{{ item.name }}"
        number: "{{ item.partition }}"
        flags: [ lvm ]
        state: present
        part_start: "{{ local_cache_disk.size }}"
        part_end: "{{ item.size | default('100%')}}"
      loop: "{{ distributed_cache_disks }}"
      register: distributed_cache_partitions
    - name: Display disks
      debug:
        msg: "{{ item.name }}"
      loop: "{{ distributed_cache_disks | flatten(1) }}"
    - name: Display local cache partition
      debug:
        msg: "{{ local_cache_partition.partitions[0] }}"
    - name: Display distributed cache partitions
      debug:
        msg: "{{ distributed_cache_partitions}}"
    - name: create volume group for local cache
      lvg:
        vg: csi-lvm-local-cache
        pvs: "{{ local_cache_disk.name }}"
    - name: create volume group for distributed cache
      lvg:
        vg: csi-lvm-distributed-cache
        pvs: "{{ item.name }}"
        state: present
      loop: "{{ distributed_cache_disks | flatten(1) }}"
    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present