#local_cache_disk:
#  name: /dev/nvme1n1p1
#  partition: 1
#  size: 150GiB
#distributed_cache_disks:
#  - name: /dev/nvme1n1p1
#    partition: 2
#    size: 100%
---

- hosts: localhost
  tasks:
    - name: create partition for local cache
      parted:
        device: "{{ local_cache_disk.device }}"
        number: "{{ local_cache_disk.number | default(1) }}"
        flags: [ lvm ]
        state: present
        part_end: "{{ local_cache_disk.part_end }}"
      register: local_cache_partition
    - name: create partitions for distributed cache
      parted:
        device: "{{ item.device }}"
        number: "{{ item.number }}"
        flags: [ lvm ]
        state: present
        part_start: "{{ item.part_start | default('0%')}}"
        part_end: "{{ item.part_end | default('100%')}}"
      loop: "{{ distributed_cache_disks }}"
      register: distributed_cache_partitions
   # - name: Create a list of distributed cache partitions
   #   set_fact:
   #     distrib_partition_list = "{{ distrib_partition_list|default([]) + [~ item.item.device ~ 'p' ~ item.item.number ~] }}"
   #   loop: "{{ distributed_cache_partitions.results }}"
    - set_fact:
        distrib_partitions_list: |-
          [
          {% for partition in distributed_cache_partitions.results %}
            "{{ partition.item.device}}p{{ partition.item.number }}",
          {% endfor %}
          ]
    - name: Display distributed cache partitions
      debug:
        var: distrib_partitions_list
    - name: create volume group for local cache
      lvg:
        vg: csi-lvm-local-cache
        pvs: "{{ local_cache_partition.disk.dev }}p{{ local_cache_partition.partitions[0].num }}"
    - name: create volume group for distributed cache
      lvg:
        vg: csi-lvm-distributed-cache
        pvs: "{{ distributed_cache_partitions.results[0].item.name }}p{{ distributed_cache_partitions.results[0].item.partition }}"
        state: present
    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present