all:
  hosts:
    node1:
      ansible_host: 10.20.72.4
      ip: 10.20.72.4
      access_ip: 10.20.72.4
      ansible_user: sysops
    node2:
      ansible_host: 10.20.72.5
      ip: 10.20.72.5
      access_ip: 10.20.72.5
      ansible_user: sysops
    node3:
      ansible_host: 10.20.72.6
      ip: 10.20.72.6
      access_ip: 10.20.72.6
      ansible_user: sysops
    node4:
      ansible_host: 10.20.72.7
      ip: 10.20.72.7
      access_ip: 10.20.72.7
      ansible_user: sysops
    node5:
      ansible_host: 10.20.72.8
      ip: 10.20.72.8
      access_ip: 10.20.72.8
      ansible_user: sysops
    node6:
      ansible_host: 10.20.72.9
      ip: 10.20.72.9
      access_ip: 10.20.72.9
      ansible_user: sysops
    node7:
      ansible_host: 10.20.75.62
      ip: 10.20.75.62
      access_ip: 10.20.75.62
      ansible_user: sysops
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
