all:
  hosts:
    node1:
      ansible_host: 10.66.1.243
      ip: 10.66.1.243
      access_ip: 10.66.1.243
      ansible_user: sysops
      ansible_ssh_private_key_file: "{{ node_ssh_private_key_file }}"
    node2:
      ansible_host: 10.66.1.152
      ip: 10.66.1.152
      access_ip: 10.66.1.152
      ansible_user: sysops
      ansible_ssh_private_key_file: "{{ node_ssh_private_key_file }}"
    node3:
      ansible_host: 10.66.1.25
      ip: 10.66.1.25
      access_ip: 10.66.1.25
      ansible_user: sysops
      ansible_ssh_private_key_file: "{{ node_ssh_private_key_file }}"
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
